project_id = "nwpgbnzvydweexruckpt"

[functions.process-documents-with-ai]
verify_jwt = false

[functions.ai-financial-insights]
verify_jwt = false

[functions.ai-case-analysis]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.detect-special-situation]
verify_jwt = false